kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.20.1
forge_version=47.3.0
java_version=17

mod_id=dye_the_world
mod_version=0.0.0-dev
release_type=release
mod_name=Dye The World!
mod_author=possible_triangle
maven_group=com.possible-triangle

jei_version=15.20.0.106
flywheel_version=1.0.1
create_version=6.0.2-52
ponder_version=1.0.43
registrate_version=MC1.20-1.3.3
kotlin_forge_version=4.3.0
dye_depot_version=cdGlC270
supplementaries_version=bHRxbeqq
moonlight_lib_version=mZqdBCnQ
another_furniture_version=aR6kgnDf
comforts_version=gBDsc134
supplementaries_squared_version=QqMQ0LSA
quark_version=vIWYw2yn
zeta_version=MRyLCiek
jade_version=oWwzG652
farmers_delight_version=AxgOboGq
clayworks_version=4B8NKv1f
upgrade_aquatic_version=zlrhxqCv
blueprint_version=D4gcSnZh
gallery_version=y24FMfgI
alexs_caves_version=lC8HHXOF
domestication_innovation_version=SGxCLghg
citadel_version=mL5pYWWo
chalk_version=YhueAXpz
create_deco_version=lcpO5tBr
create_railways_version=pklcGSDf
curios_version=QBtodtmR
ars_nouveau_version=qtW93rN7
mixin_extras_version=0.4.1
more_concrete_version=xBAEvv9U
alexs_mobs_version=XoIASRVU
waystones_version=WKyfSzs9
balm_version=za1mJSJs

repository=pssbletrngle/dyetheworld
modrinth_project_id=naUMeOvG
curseforge_project_id=1135725