modLoader = "kotlinforforge"
loaderVersion = "[4.3.0,)"
license = "https://github.com/${repository}/blob/1.20.x/LICENSE.txt"
issueTrackerURL = "https://github.com/${repository}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''Compatiblity for the Dye Depot mod'''
updateJSONURL = "https://api.modrinth.com/updates/dye-the-world/forge_updates.json"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="kotlinforforge"
mandatory=true
versionRange="[4.3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dye_depot"
mandatory=true
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = false
versionRange = "[0.5.1.e,)"
ordering="AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "another_furniture"
mandatory = false
versionRange = "*"
ordering="AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "supplementaries"
mandatory = false
versionRange = "*"
ordering="AFTER"
side = "BOTH"